export interface Landdata {
  alpha3: string;
  nb: string;
  nn: string;
  en: string;
}

export const landliste: ReadonlyArray<Landdata> = [
  { alpha3: 'AFG', nb: 'Afghanistan', nn: 'Afghanistan', en: 'Afghanistan' },
  { alpha3: 'AGO', nb: 'Angola', nn: 'Angola', en: 'Angola' },
  { alpha3: 'ALB', nb: 'Albania', nn: 'Albania', en: 'Albania' },
  { alpha3: 'AND', nb: 'Andorra', nn: 'Andorra', en: 'Andorra' },
  {
    alpha3: 'ARE',
    nb: 'De forente arabiske emirater',
    nn: 'Dei sameinte arabiske emirata',
    en: 'United Arab Emirates',
  },
  { alpha3: 'ARG', nb: 'Argentina', nn: 'Argentina', en: 'Argentina' },
  { alpha3: 'ARM', nb: 'Armenia', nn: 'Armenia', en: 'Armenia' },
  { alpha3: 'ATG', nb: 'Antigua og Barbuda', nn: 'Antigua og Barbuda', en: 'Antigua and Barbuda' },
  { alpha3: 'AUS', nb: 'Australia', nn: 'Australia', en: 'Australia' },
  { alpha3: 'AUT', nb: 'Østerrike', nn: 'Austerrike', en: 'Austria' },
  { alpha3: 'AZE', nb: 'Aserbajdsjan', nn: 'Aserbajdsjan', en: 'Azerbaijan' },
  { alpha3: 'BDI', nb: 'Burundi', nn: 'Burundi', en: 'Burundi' },
  { alpha3: 'BEL', nb: 'Belgia', nn: 'Belgia', en: 'Belgium' },
  { alpha3: 'BEN', nb: 'Benin', nn: 'Benin', en: 'Benin' },
  { alpha3: 'BFA', nb: 'Burkina Faso', nn: 'Burkina Faso', en: 'Burkina Faso' },
  { alpha3: 'BGD', nb: 'Bangladesh', nn: 'Bangladesh', en: 'Bangladesh' },
  { alpha3: 'BGR', nb: 'Bulgaria', nn: 'Bulgaria', en: 'Bulgaria' },
  { alpha3: 'BHR', nb: 'Bahrain', nn: 'Bahrain', en: 'Bahrain' },
  { alpha3: 'BHS', nb: 'Bahamas', nn: 'Bahamas', en: 'Bahamas' },
  {
    alpha3: 'BIH',
    nb: 'Bosnia-Hercegovina',
    nn: 'Bosnia-Hercegovina',
    en: 'Bosnia and Herzegovina',
  },
  { alpha3: 'BLR', nb: 'Hviterussland', nn: 'Kviterussland', en: 'Belarus' },
  { alpha3: 'BLZ', nb: 'Belize', nn: 'Belize', en: 'Belize' },
  { alpha3: 'BOL', nb: 'Bolivia', nn: 'Bolivia', en: 'Bolivia' },
  { alpha3: 'BRA', nb: 'Brasil', nn: 'Brasil', en: 'Brazil' },
  { alpha3: 'BRB', nb: 'Barbados', nn: 'Barbados', en: 'Barbados' },
  { alpha3: 'BRN', nb: 'Brunei', nn: 'Brunei', en: 'Brunei Darussalam' },
  { alpha3: 'BTN', nb: 'Bhutan', nn: 'Bhutan', en: 'Bhutan' },
  { alpha3: 'BWA', nb: 'Botswana', nn: 'Botswana', en: 'Botswana' },
  {
    alpha3: 'CAF',
    nb: 'Den sentralafrikanske republikk',
    nn: 'Den sentralafrikanske republikken',
    en: 'Central African Republic',
  },
  { alpha3: 'CAN', nb: 'Canada', nn: 'Canada', en: 'Canada' },
  { alpha3: 'CHE', nb: 'Sveits', nn: 'Sveits', en: 'Switzerland' },
  { alpha3: 'CHL', nb: 'Chile', nn: 'Chile', en: 'Chile' },
  { alpha3: 'CHN', nb: 'Kina', nn: 'Kina', en: "People's Republic of China" },
  { alpha3: 'CIV', nb: 'Elfenbenskysten', nn: 'Elfenbeinskysten', en: "Cote d'Ivoire" },
  { alpha3: 'CMR', nb: 'Kamerun', nn: 'Kamerun', en: 'Cameroon' },
  { alpha3: 'COD', nb: 'Kongo', nn: 'Kongo', en: 'Democratic Republic of the Congo' },
  { alpha3: 'COG', nb: 'Kongo-Brazzaville', nn: 'Kongo-Brazzaville', en: 'Republic of the Congo' },
  { alpha3: 'COL', nb: 'Colombia', nn: 'Colombia', en: 'Colombia' },
  { alpha3: 'COM', nb: 'Komorene', nn: 'Komorane', en: 'Comoros' },
  { alpha3: 'CPV', nb: 'Kapp Verde', nn: 'Kapp Verde', en: 'Cape Verde' },
  { alpha3: 'CRI', nb: 'Costa Rica', nn: 'Costa Rica', en: 'Costa Rica' },
  { alpha3: 'CUB', nb: 'Cuba', nn: 'Cuba', en: 'Cuba' },
  { alpha3: 'CYP', nb: 'Kypros', nn: 'Kypros', en: 'Cyprus' },
  { alpha3: 'CZE', nb: 'Tsjekkia', nn: 'Tsjekkia', en: 'Czech Republic' },
  { alpha3: 'DEU', nb: 'Tyskland', nn: 'Tyskland', en: 'Germany' },
  { alpha3: 'DJI', nb: 'Djibouti', nn: 'Djibouti', en: 'Djibouti' },
  { alpha3: 'DMA', nb: 'Dominica', nn: 'Dominica', en: 'Dominica' },
  { alpha3: 'DNK', nb: 'Danmark', nn: 'Danmark', en: 'Denmark' },
  {
    alpha3: 'DOM',
    nb: 'Den dominikanske republikk',
    nn: 'Den dominikanske republikken',
    en: 'Dominican Republic',
  },
  { alpha3: 'DZA', nb: 'Algerie', nn: 'Algerie', en: 'Algeria' },
  { alpha3: 'ECU', nb: 'Ecuador', nn: 'Ecuador', en: 'Ecuador' },
  { alpha3: 'EGY', nb: 'Egypt', nn: 'Egypt', en: 'Egypt' },
  { alpha3: 'ERI', nb: 'Eritrea', nn: 'Eritrea', en: 'Eritrea' },
  { alpha3: 'ESP', nb: 'Spania', nn: 'Spania', en: 'Spain' },
  { alpha3: 'EST', nb: 'Estland', nn: 'Estland', en: 'Estonia' },
  { alpha3: 'ETH', nb: 'Etiopia', nn: 'Etiopia', en: 'Ethiopia' },
  { alpha3: 'FIN', nb: 'Finland', nn: 'Finland', en: 'Finland' },
  { alpha3: 'FJI', nb: 'Fiji', nn: 'Fiji', en: 'Fiji' },
  { alpha3: 'FRA', nb: 'Frankrike', nn: 'Frankrike', en: 'France' },
  {
    alpha3: 'FSM',
    nb: 'Mikronesiaføderasjonen',
    nn: 'Mikronesiaføderasjonen',
    en: 'Micronesia, Federated States of',
  },
  { alpha3: 'GAB', nb: 'Gabon', nn: 'Gabon', en: 'Gabon' },
  { alpha3: 'GBR', nb: 'Storbritannia', nn: 'Storbritannia', en: 'United Kingdom' },
  { alpha3: 'GEO', nb: 'Georgia', nn: 'Georgia', en: 'Georgia' },
  { alpha3: 'GHA', nb: 'Ghana', nn: 'Ghana', en: 'Ghana' },
  { alpha3: 'GIN', nb: 'Guinea', nn: 'Guinea', en: 'Guinea' },
  { alpha3: 'GMB', nb: 'Gambia', nn: 'Gambia', en: 'Republic of The Gambia' },
  { alpha3: 'GNB', nb: 'Guinea-Bissau', nn: 'Guinea-Bissau', en: 'Guinea-Bissau' },
  { alpha3: 'GNQ', nb: 'Ekvatorial-Guinea', nn: 'Ekvatorial-Guinea', en: 'Equatorial Guinea' },
  { alpha3: 'GRC', nb: 'Hellas', nn: 'Hellas', en: 'Greece' },
  { alpha3: 'GRD', nb: 'Grenada', nn: 'Grenada', en: 'Grenada' },
  { alpha3: 'GTM', nb: 'Guatemala', nn: 'Guatemala', en: 'Guatemala' },
  { alpha3: 'GUY', nb: 'Guyana', nn: 'Guyana', en: 'Guyana' },
  { alpha3: 'HND', nb: 'Honduras', nn: 'Honduras', en: 'Honduras' },
  { alpha3: 'HRV', nb: 'Kroatia', nn: 'Kroatia', en: 'Croatia' },
  { alpha3: 'HTI', nb: 'Haiti', nn: 'Haiti', en: 'Haiti' },
  { alpha3: 'HUN', nb: 'Ungarn', nn: 'Ungarn', en: 'Hungary' },
  { alpha3: 'IDN', nb: 'Indonesia', nn: 'Indonesia', en: 'Indonesia' },
  { alpha3: 'IND', nb: 'India', nn: 'India', en: 'India' },
  { alpha3: 'IRL', nb: 'Irland', nn: 'Irland', en: 'Ireland' },
  { alpha3: 'IRN', nb: 'Iran', nn: 'Iran', en: 'Islamic Republic of Iran' },
  { alpha3: 'IRQ', nb: 'Irak', nn: 'Irak', en: 'Iraq' },
  { alpha3: 'ISL', nb: 'Island', nn: 'Island', en: 'Iceland' },
  { alpha3: 'ISR', nb: 'Israel', nn: 'Israel', en: 'Israel' },
  { alpha3: 'ITA', nb: 'Italia', nn: 'Italia', en: 'Italy' },
  { alpha3: 'JAM', nb: 'Jamaica', nn: 'Jamaica', en: 'Jamaica' },
  { alpha3: 'JOR', nb: 'Jordan', nn: 'Jordan', en: 'Jordan' },
  { alpha3: 'JPN', nb: 'Japan', nn: 'Japan', en: 'Japan' },
  { alpha3: 'KAZ', nb: 'Kasakhstan', nn: 'Kasakhstan', en: 'Kazakhstan' },
  { alpha3: 'KEN', nb: 'Kenya', nn: 'Kenya', en: 'Kenya' },
  { alpha3: 'KGZ', nb: 'Kirgisistan', nn: 'Kirgisistan', en: 'Kyrgyzstan' },
  { alpha3: 'KHM', nb: 'Kambodsja', nn: 'Kambodsja', en: 'Cambodia' },
  { alpha3: 'KIR', nb: 'Kiribati', nn: 'Kiribati', en: 'Kiribati' },
  {
    alpha3: 'KNA',
    nb: 'Saint Kitts og Nevis',
    nn: 'Saint Kitts og Nevis',
    en: 'Saint Kitts and Nevis',
  },
  { alpha3: 'KOR', nb: 'Sør-Korea', nn: 'Sør-Korea', en: 'South Korea' },
  { alpha3: 'KWT', nb: 'Kuwait', nn: 'Kuwait', en: 'Kuwait' },
  { alpha3: 'LAO', nb: 'Laos', nn: 'Laos', en: "Lao People's Democratic Republic" },
  { alpha3: 'LBN', nb: 'Libanon', nn: 'Libanon', en: 'Lebanon' },
  { alpha3: 'LBR', nb: 'Liberia', nn: 'Liberia', en: 'Liberia' },
  { alpha3: 'LBY', nb: 'Libya', nn: 'Libya', en: 'Libya' },
  { alpha3: 'LCA', nb: 'Saint Lucia', nn: 'Saint Lucia', en: 'Saint Lucia' },
  { alpha3: 'LIE', nb: 'Liechtenstein', nn: 'Liechtenstein', en: 'Liechtenstein' },
  { alpha3: 'LKA', nb: 'Sri Lanka', nn: 'Sri Lanka', en: 'Sri Lanka' },
  { alpha3: 'LSO', nb: 'Lesotho', nn: 'Lesotho', en: 'Lesotho' },
  { alpha3: 'LTU', nb: 'Litauen', nn: 'Litauen', en: 'Lithuania' },
  { alpha3: 'LUX', nb: 'Luxembourg', nn: 'Luxembourg', en: 'Luxembourg' },
  { alpha3: 'LVA', nb: 'Latvia', nn: 'Latvia', en: 'Latvia' },
  { alpha3: 'MAR', nb: 'Marokko', nn: 'Marokko', en: 'Morocco' },
  { alpha3: 'MCO', nb: 'Monaco', nn: 'Monaco', en: 'Monaco' },
  { alpha3: 'MDA', nb: 'Moldova', nn: 'Moldova', en: 'Moldova, Republic of' },
  { alpha3: 'MDG', nb: 'Madagaskar', nn: 'Madagaskar', en: 'Madagascar' },
  { alpha3: 'MDV', nb: 'Maldivene', nn: 'Maldivane', en: 'Maldives' },
  { alpha3: 'MEX', nb: 'Mexico', nn: 'Mexico', en: 'Mexico' },
  { alpha3: 'MHL', nb: 'Marshalløyene', nn: 'Marshalløyane', en: 'Marshall Islands' },
  {
    alpha3: 'MKD',
    nb: 'Nord-Makedonia',
    nn: 'Nord-Makedonia',
    en: 'The Republic of North Macedonia',
  },
  { alpha3: 'MLI', nb: 'Mali', nn: 'Mali', en: 'Mali' },
  { alpha3: 'MLT', nb: 'Malta', nn: 'Malta', en: 'Malta' },
  { alpha3: 'MMR', nb: 'Myanmar (Burma)', nn: 'Myanmar (Burma)', en: 'Myanmar' },
  { alpha3: 'MNE', nb: 'Montenegro', nn: 'Montenegro', en: 'Montenegro' },
  { alpha3: 'MNG', nb: 'Mongolia', nn: 'Mongolia', en: 'Mongolia' },
  { alpha3: 'MOZ', nb: 'Mosambik', nn: 'Mosambik', en: 'Mozambique' },
  { alpha3: 'MRT', nb: 'Mauritania', nn: 'Mauritania', en: 'Mauritania' },
  { alpha3: 'MUS', nb: 'Mauritius', nn: 'Mauritius', en: 'Mauritius' },
  { alpha3: 'MWI', nb: 'Malawi', nn: 'Malawi', en: 'Malawi' },
  { alpha3: 'MYS', nb: 'Malaysia', nn: 'Malaysia', en: 'Malaysia' },
  { alpha3: 'NAM', nb: 'Namibia', nn: 'Namibia', en: 'Namibia' },
  { alpha3: 'NER', nb: 'Niger', nn: 'Niger', en: 'Niger' },
  { alpha3: 'NGA', nb: 'Nigeria', nn: 'Nigeria', en: 'Nigeria' },
  { alpha3: 'NIC', nb: 'Nicaragua', nn: 'Nicaragua', en: 'Nicaragua' },
  { alpha3: 'NLD', nb: 'Nederland', nn: 'Nederland', en: 'Netherlands' },
  { alpha3: 'NOR', nb: 'Norge', nn: 'Noreg', en: 'Norway' },
  { alpha3: 'NPL', nb: 'Nepal', nn: 'Nepal', en: 'Nepal' },
  { alpha3: 'NRU', nb: 'Nauru', nn: 'Nauru', en: 'Nauru' },
  { alpha3: 'NZL', nb: 'New Zealand', nn: 'New Zealand', en: 'New Zealand' },
  { alpha3: 'OMN', nb: 'Oman', nn: 'Oman', en: 'Oman' },
  { alpha3: 'PAK', nb: 'Pakistan', nn: 'Pakistan', en: 'Pakistan' },
  { alpha3: 'PAN', nb: 'Panama', nn: 'Panama', en: 'Panama' },
  { alpha3: 'PER', nb: 'Peru', nn: 'Peru', en: 'Peru' },
  { alpha3: 'PHL', nb: 'Filippinene', nn: 'Filippinane', en: 'Philippines' },
  { alpha3: 'PLW', nb: 'Palau', nn: 'Palau', en: 'Palau' },
  { alpha3: 'PNG', nb: 'Papua Ny-Guinea', nn: 'Papua Ny-Guinea', en: 'Papua New Guinea' },
  { alpha3: 'POL', nb: 'Polen', nn: 'Polen', en: 'Poland' },
  { alpha3: 'PRK', nb: 'Nord-Korea', nn: 'Nord-Korea', en: 'North Korea' },
  { alpha3: 'PRT', nb: 'Portugal', nn: 'Portugal', en: 'Portugal' },
  { alpha3: 'PRY', nb: 'Paraguay', nn: 'Paraguay', en: 'Paraguay' },
  {
    alpha3: 'PSE',
    nb: 'De okkuperte palestinske områdene',
    nn: 'Dei okkuperte palestinske områda',
    en: 'State of Palestine',
  },
  { alpha3: 'QAT', nb: 'Qatar', nn: 'Qatar', en: 'Qatar' },
  { alpha3: 'ROU', nb: 'Romania', nn: 'Romania', en: 'Romania' },
  { alpha3: 'RUS', nb: 'Russland', nn: 'Russland', en: 'Russian Federation' },
  { alpha3: 'RWA', nb: 'Rwanda', nn: 'Rwanda', en: 'Rwanda' },
  { alpha3: 'SAU', nb: 'Saudi-Arabia', nn: 'Saudi-Arabia', en: 'Saudi Arabia' },
  { alpha3: 'SDN', nb: 'Sudan', nn: 'Sudan', en: 'Sudan' },
  { alpha3: 'SEN', nb: 'Senegal', nn: 'Senegal', en: 'Senegal' },
  { alpha3: 'SGP', nb: 'Singapore', nn: 'Singapore', en: 'Singapore' },
  { alpha3: 'SLB', nb: 'Salomonøyene', nn: 'Salomonøyane', en: 'Solomon Islands' },
  { alpha3: 'SLE', nb: 'Sierra Leone', nn: 'Sierra Leone', en: 'Sierra Leone' },
  { alpha3: 'SLV', nb: 'El Salvador', nn: 'El Salvador', en: 'El Salvador' },
  { alpha3: 'SMR', nb: 'San Marino', nn: 'San Marino', en: 'San Marino' },
  { alpha3: 'SOM', nb: 'Somalia', nn: 'Somalia', en: 'Somalia' },
  { alpha3: 'SRB', nb: 'Serbia', nn: 'Serbia', en: 'Serbia' },
  { alpha3: 'SSD', nb: 'Sør-Sudan', nn: 'Sør-Sudan', en: 'South Sudan' },
  {
    alpha3: 'STP',
    nb: 'São Tomé og Príncipe',
    nn: 'São Tomé og Príncipe',
    en: 'Sao Tome and Principe',
  },
  { alpha3: 'SUR', nb: 'Surinam', nn: 'Surinam', en: 'Suriname' },
  { alpha3: 'SVK', nb: 'Slovakia', nn: 'Slovakia', en: 'Slovakia' },
  { alpha3: 'SVN', nb: 'Slovenia', nn: 'Slovenia', en: 'Slovenia' },
  { alpha3: 'SWE', nb: 'Sverige', nn: 'Sverige', en: 'Sweden' },
  { alpha3: 'SWZ', nb: 'Eswatini', nn: 'Eswatini', en: 'Eswatini' },
  { alpha3: 'SYC', nb: 'Seychellene', nn: 'Seychellane', en: 'Seychelles' },
  { alpha3: 'SYR', nb: 'Syria', nn: 'Syria', en: 'Syrian Arab Republic' },
  { alpha3: 'TCD', nb: 'Tsjad', nn: 'Tsjad', en: 'Chad' },
  { alpha3: 'TGO', nb: 'Togo', nn: 'Togo', en: 'Togo' },
  { alpha3: 'THA', nb: 'Thailand', nn: 'Thailand', en: 'Thailand' },
  { alpha3: 'TJK', nb: 'Tadsjikistan', nn: 'Tadsjikistan', en: 'Tajikistan' },
  { alpha3: 'TKM', nb: 'Turkmenistan', nn: 'Turkmenistan', en: 'Turkmenistan' },
  { alpha3: 'TLS', nb: 'Øst-Timor', nn: 'Aust-Timor', en: 'Timor-Leste' },
  { alpha3: 'TON', nb: 'Tonga', nn: 'Tonga', en: 'Tonga' },
  { alpha3: 'TTO', nb: 'Trinidad og Tobago', nn: 'Trinidad og Tobago', en: 'Trinidad and Tobago' },
  { alpha3: 'TUN', nb: 'Tunisia', nn: 'Tunisia', en: 'Tunisia' },
  { alpha3: 'TUR', nb: 'Tyrkia', nn: 'Tyrkia', en: 'Türkiye' },
  { alpha3: 'TUV', nb: 'Tuvalu', nn: 'Tuvalu', en: 'Tuvalu' },
  { alpha3: 'TZA', nb: 'Tanzania', nn: 'Tanzania', en: 'United Republic of Tanzania' },
  { alpha3: 'UGA', nb: 'Uganda', nn: 'Uganda', en: 'Uganda' },
  { alpha3: 'UKR', nb: 'Ukraina', nn: 'Ukraina', en: 'Ukraine' },
  { alpha3: 'URY', nb: 'Uruguay', nn: 'Uruguay', en: 'Uruguay' },
  { alpha3: 'USA', nb: 'USA', nn: 'USA', en: 'United States of America' },
  { alpha3: 'UZB', nb: 'Usbekistan', nn: 'Usbekistan', en: 'Uzbekistan' },
  { alpha3: 'VAT', nb: 'Vatikanstaten', nn: 'Vatikanstaten', en: 'Holy See (Vatican City State)' },
  {
    alpha3: 'VCT',
    nb: 'Saint Vincent og Grenadinene',
    nn: 'Saint Vincent og Grenadinane',
    en: 'Saint Vincent and the Grenadines',
  },
  { alpha3: 'VEN', nb: 'Venezuela', nn: 'Venezuela', en: 'Venezuela' },
  { alpha3: 'VNM', nb: 'Vietnam', nn: 'Vietnam', en: 'Vietnam' },
  { alpha3: 'VUT', nb: 'Vanuatu', nn: 'Vanuatu', en: 'Vanuatu' },
  { alpha3: 'WSM', nb: 'Samoa', nn: 'Samoa', en: 'Samoa' },
  { alpha3: 'XKX', nb: 'Kosovo', nn: 'Kosovo', en: 'Kosovo' },
  { alpha3: 'YEM', nb: 'Jemen', nn: 'Jemen', en: 'Yemen' },
  { alpha3: 'ZAF', nb: 'Sør-Afrika', nn: 'Sør-Afrika', en: 'South Africa' },
  { alpha3: 'ZMB', nb: 'Zambia', nn: 'Zambia', en: 'Zambia' },
  { alpha3: 'ZWE', nb: 'Zimbabwe', nn: 'Zimbabwe', en: 'Zimbabwe' },
];

export const eøsLandKoder: ReadonlyArray<string> = [
  'AUT',
  'BEL',
  'BGR',
  'CYP',
  'CZE',
  'DEU',
  'DNK',
  'ESP',
  'EST',
  'FIN',
  'FRA',
  'GRC',
  'HRV',
  'HUN',
  'IRL',
  'ISL',
  'ITA',
  'LIE',
  'LTU',
  'LUX',
  'LVA',
  'MLT',
  'NLD',
  'NOR',
  'POL',
  'PRT',
  'ROU',
  'SVK',
  'SVN',
  'SWE',
];
